version: '3'

networks: 
  poll-tier:
    name: poll-tier
  result-tier:
    name: result-tier
  back-tier:
    name: back-tier

services:
  poll:
    build: ./poll
    links:
      - redis
      - db
    restart: always
    ports:
      - 5000:80
    networks:
      - poll-tier
    environement:
      - 0.0.0.0

  redis:
    image: redis
    restart: always
    ports:
      - 6379
    networks:
      - poll-tier
      - back-tier
  
  worker:
    build: ./worker
    links:
      - redis
      - db
    restart: always
    networks:
      - back-tier
    environment:
      - 0.0.0.0

  db:
    image : postgres
    restart : always
    networks:
      - result-tier
      - back-tier
    environement:
      - POSTGRES_PASSWORK=password

  result:
    build: ./result
    depends_on:
      - db
    restart: always
    ports:
      - 5001:80
    networks:
      - result-tier
    environement:
      - 0.0.0.0

volumes:
  db-data: